apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec: echo "Hello from client" | nc nodejs-service 1234
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
